# Generated by Django 4.0.6 on 2025-07-20 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('correo_cliente', models.EmailField(max_length=254)),
                ('fecha_registro_cliente', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electrodomestico',
            fields=[
                ('id_electrodomestico', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_electrodomestico', models.CharField(max_length=100)),
                ('marca_electrodomestico', models.CharField(max_length=100)),
                ('modelo_electrodomestico', models.CharField(max_length=100)),
                ('descripcion_falla_electrodomestico', models.TextField()),
                ('fecha_ingreso_electrodomestico', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrodomesticos', to='proyecto.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_login', models.CharField(max_length=100, unique=True)),
                ('contrasena_login', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tecnico', models.CharField(max_length=100)),
                ('especialidad_tecnico', models.CharField(max_length=100)),
                ('telefono_tecnico', models.CharField(max_length=20)),
                ('correo_tecnico', models.EmailField(max_length=254)),
                ('fecha_contratacion_tecnico', models.DateField()),
                ('id_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='proyecto.login')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_servicio_servicio', models.TextField()),
                ('costo_estimado_servicio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado_servicio', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('fecha_inicio_servicio', models.DateField()),
                ('fecha_fin_servicio', models.DateField(blank=True, null=True)),
                ('id_electrodomestico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='proyecto.electrodomestico')),
                ('id_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='proyecto.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision_factura', models.DateField(auto_now_add=True)),
                ('monto_total_factura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagado_factura', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=50)),
                ('estado_factura', models.CharField(choices=[('Vigente', 'Vigente'), ('Expirada', 'Expirada')], max_length=50)),
                ('tiempo_factura', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='proyecto.cliente')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='proyecto.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='proyecto.login'),
        ),
    ]
