# Generated by Django 4.0.6 on 2025-07-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contrasena_usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
